version: '3'

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: always
        ports:
            - "15672:15672"
            - "5672:5672"
        environment:
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq

    jobmanager:
        image: flink
        container_name: jobmanager
        ports:
            - "8081:8081"
        expose:
            - "6123"
        command: jobmanager
        environment:
            - JOB_MANAGER_RPC_ADDRESS=jobmanager
        volumes:
            - ./consumer/consumer:/app
            - ./results:/results

    taskmanager1:
        image: flink
        container_name: taskmanager1
        expose:
            - "6121"
            - "6122"
        depends_on:
            - jobmanager
        command: taskmanager
        links:
            - "jobmanager:jobmanager"
        environment:
            - JOB_MANAGER_RPC_ADDRESS=jobmanager
        volumes:
            - ./results:/results

    taskmanager2:
        image: flink
        container_name: taskmanager2
        expose:
            - "6121"
            - "6122"
        depends_on:
            - jobmanager
        command: taskmanager
        links:
            - "jobmanager:jobmanager"
        environment:
            - JOB_MANAGER_RPC_ADDRESS=jobmanager
        volumes:
            - ./results:/results

    taskmanager3:
        image: flink
        container_name: taskmanager3
        expose:
            - "6121"
            - "6122"
        depends_on:
            - jobmanager
        command: taskmanager
        links:
            - "jobmanager:jobmanager"
        environment:
            - JOB_MANAGER_RPC_ADDRESS=jobmanager
        volumes:
            - ./results:/results

    producer:
        build:
            context: .
            dockerfile: ./producer/dockerfile
        volumes:
            - ./producer/app:/app
        links:
            - rabbitmq:rabbitmq
        environment:
            - RABBITMQ_USER=rabbitmq
            - RABBITMQ_PASS=rabbitmq


    mongo:
        image: mongo
        restart: always
        ports:
        - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: mongo
          MONGO_INITDB_ROOT_PASSWORD: mongo

    mongo-express:
      image: mongo-express
      restart: always
      ports:
      - 8082:8081
      links:
        - mongo:mongo

      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
        ME_CONFIG_MONGODB_ADMINPASSWORD: mongo

    mongoconsumer:
        build:
            context: .
            dockerfile: ./mongoconsumer/dockerfile
        volumes:
            - ./mongoconsumer/app:/app
        links:
            - rabbitmq:rabbitmq
            - mongo:mongo
        environment:
            - RABBITMQ_USER=rabbitmq
            - RABBITMQ_PASS=rabbitmq
